// Next.js static export style - SSG pattern
// Simulates a Next.js static export with pages

export async function fetch(request) {
  const url = new URL(request.url);
  
  // Simulate Next.js pages routing
  if (url.pathname === '/') {
    return new Response(`
<!DOCTYPE html>
<html>
<head><title>Next.js Static Export</title></head>
<body>
  <h1>Next.js Static Export Demo</h1>
  <p>This simulates a Next.js static export serving HTML.</p>
  <ul>
    <li><a href="/about">/about</a></li>
    <li><a href="/blog">/blog</a></li>
  </ul>
</body>
</html>
    `.trim(), {
      headers: { 'Content-Type': 'text/html' }
    });
  }
  
  if (url.pathname === '/about') {
    return new Response(`
<!DOCTYPE html>
<html>
<head><title>About - Next.js</title></head>
<body>
  <h1>About Page</h1>
  <p>Statically generated by Next.js export.</p>
</body>
</html>
    `.trim(), {
      headers: { 'Content-Type': 'text/html' }
    });
  }
  
  if (url.pathname === '/blog') {
    return new Response(`
<!DOCTYPE html>
<html>
<head><title>Blog - Next.js</title></head>
<body>
  <h1>Blog</h1>
  <article>
    <h2>First Post</h2>
    <p>Content from static generation.</p>
  </article>
</body>
</html>
    `.trim(), {
      headers: { 'Content-Type': 'text/html' }
    });
  }
  
  // API routes pattern
  if (url.pathname.startsWith('/api/')) {
    return new Response(JSON.stringify({
      nextjs: true,
      api: true,
      path: url.pathname,
      timestamp: Date.now()
    }), {
      headers: { 'Content-Type': 'application/json' }
    });
  }
  
  return new Response('404 - Page Not Found', { status: 404 });
}
